[project]
name = "cel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mypy-protobuf>=3.6.0",
    "protobuf==6.31.0",
]
