"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import cel.expr.conformance.proto2.test_all_types_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.extension_dict
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Proto2ExtensionScopedMessage(google.protobuf.message.Message):
    """Message scoped extensions"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INT64_EXT_FIELD_NUMBER: builtins.int
    MESSAGE_SCOPED_NESTED_EXT_FIELD_NUMBER: builtins.int
    NESTED_ENUM_EXT_FIELD_NUMBER: builtins.int
    MESSAGE_SCOPED_REPEATED_TEST_ALL_TYPES_FIELD_NUMBER: builtins.int
    int64_ext: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes, builtins.int]
    message_scoped_nested_ext: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes, cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes]
    nested_enum_ext: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes, cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes.NestedEnum.ValueType]
    message_scoped_repeated_test_all_types: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes, google.protobuf.internal.containers.RepeatedCompositeFieldContainer[cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes]]
    def __init__(
        self,
    ) -> None: ...

global___Proto2ExtensionScopedMessage = Proto2ExtensionScopedMessage

INT32_EXT_FIELD_NUMBER: builtins.int
NESTED_EXT_FIELD_NUMBER: builtins.int
TEST_ALL_TYPES_EXT_FIELD_NUMBER: builtins.int
NESTED_ENUM_EXT_FIELD_NUMBER: builtins.int
REPEATED_TEST_ALL_TYPES_FIELD_NUMBER: builtins.int
int32_ext: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes, builtins.int]
nested_ext: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes, cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes]
test_all_types_ext: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes, cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes]
nested_enum_ext: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes, cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes.NestedEnum.ValueType]
repeated_test_all_types: google.protobuf.internal.extension_dict._ExtensionFieldDescriptor[cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes, google.protobuf.internal.containers.RepeatedCompositeFieldContainer[cel.expr.conformance.proto2.test_all_types_pb2.TestAllTypes]]
